experiment:
  name: experiment1
  task_names:
    intensity: intensity
    clarity: clarity
  logistic_scale: 1.0
  standardize_scores: true
  pairwise_methods:
    - DLM_2
    - DLM_3
    - ULM_L
    - LM_L
    - LM_C
